### PR TITLE
Fix #1597 [V8.3.1 API broken when cache enable ]

### LINKED ISSUE #1597: V8.3.1 API broken when cache enable
When I enable cache by this in project setting file:

```php
    'cache' => [
        'enabled' => true,
        'response_ttl' => 300,
        'pool' => [
            'adapter' => 'filesystem',
            'path' => './cache/',
        ],
    ],
```

And try to login with admin app, then I got a `Couldn't Reach API` error at APP, and api with this:

```shell
[ERROR 0 /index.php] PHP message: PHP Notice:  Trying to access array offset on value of type int in /var/www/html/src/core/Directus/Database/TableGateway/BaseTableGateway.php on line 855
```

I have tried `filesystem` and `apcu` adapter, and both have this problem.

## Technical Details
* Device: Desktop
* OS: Windows 10 with Docker Desktop
* Web Server: Caddy 1.8
* PHP Version: 7.4
* Database: MySQL 8
* Install Method: cloned v8.3.1 tagged branch, manual build and install

### PR DESCRIPTION
**Pull request by bjgajjar**
Fixes #1597

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
What did you change and how did it fix the issue?

File: src/core/Directus/Services/AbstractService.php [hunk 1]
```diff
@@ -317,16 +316,18 @@ protected function getDataAndSetResponseCacheTags(Callable $callable, array $cal
...
-            $this->tagResponseCache('table_'.$collectionName);
+            $this->tagResponseCache('table_' . $collectionName);
             // Note: See other reference to permissions_collection_<>
             // to proper set a new tag now that group doesn't exist anymore
-            $this->tagResponseCache('permissions_collection_'.$collectionName);
+            $this->tagResponseCache('permissions_collection_' . $collectionName);
 
             foreach ($payload->getData() as $item) {
-                $this->tagResponseCache('entity_'.$collectionName.'_'.$item[$pkName]);
+                if (isset($item[$pkName])) {
```
Comment (bjgajjar) [inline src/core/Directus/Services/AbstractService.php]: @rijkvanzanten - Here is the added condition.

**Comment by rijkvanzanten** [comment]
Thanks! It was kinda hard to tell with all the automated format changes 🙂 Hopefully @jooola's PR https://github.com/directus/api/pull/1615 will fix that once and for all
