### PR TITLE
Fix #1238 [PDF support for Embedded URL]

### LINKED ISSUE #1238: File field: Embedding a file will result to Trouble processing request. Try again after refreshing the page.
## Steps to Reproduce

* Development env
* Create `pdfs` collection with `downloadable` file field
* Add pdfs item and use these links below to embed in the `downloadable` field
    * https://cdn.fileinfo.com/img/ss/lg/jpg_44.jpg
    * http://www.africau.edu/images/default/sample.pdf

## Expected Behavior

They should be embedded successfully

## Actual Behavior

`Trouble processing request. Try again after refreshing the page.`

```
Notice: Trying to get property of non-object in /src/core/Directus/Filesystem/Files.php on line 284
```

## Other Context & Screenshots

[screenrecording](https://drive.google.com/file/d/1assMeLDLxWnuqk-cbABKhfj6jdQ_dW7L/view?usp=sharing)

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.5.0 build
- Directus App: 7.10.0

### PR DESCRIPTION
**Pull request by bjgajjar**

### CODE REVIEW

File: src/core/Directus/Filesystem/Files.php [hunk 1]
```diff
@@ -195,7 +195,7 @@ protected function getImageFromURL($url)
 
         $contentType = $this->getMimeTypeFromContentType($contentType);
 
-        if (strpos($contentType, 'image/') === false) {
+        if (strpos($contentType, 'image/') === false && strpos($contentType, 'pdf') === false) {
```
Comment (hemratna) [inline src/core/Directus/Filesystem/Files.php]: Can we have an array of supported file type?

Create a sperate function which returns all the supported filetypes. 
Easy to extends.

File: src/core/Directus/Filesystem/Files.php [hunk 2]
```diff
@@ -309,8 +311,9 @@ public function saveData($fileData, $fileName, $replace = false)
             $media = json_decode($output);
             $duration = $media->format->duration;
         }
-
+        if(isset($handle)){
         fclose($handle);
```
Comment (hemratna) [inline src/core/Directus/Filesystem/Files.php]: Fix the code style.
