### PR TITLE
Fix #1735 ["Required" fails on some fields]

### LINKED ISSUE #1735: "Required" fails on some fields
v8.5.4

Altering 
image

To active state and save results in (this is from two different fields where the "truncated" file is the current filename)

image

And the result is that the fields required state is unaltered.

### PR DESCRIPTION
**Pull request by hemratna**
This PR is dependent on #1764. Please merge the PR #1764 before this one.
Also, merge the doc PR https://github.com/directus/docs/pull/295

### CODE REVIEW

File: src/core/Directus/Database/Schema/SchemaFactory.php [hunk 1]
```diff
@@ -154,6 +160,19 @@ public function alterTable($name, array $data)
         }
 
         $toChangeColumnsData = ArrayUtils::get($data, 'change', []);
+
+        // Throws an exception when trying to make the field required and there are items with no value for that field in collection
+        foreach ($toChangeColumnsData as $column) {
+            if($column['required']) {
+                $selectQuery = sprintf('SELECT * FROM `%s` WHERE `%s` IS NULL',$name,$column['field']);
```
Comment (WoLfulus) [inline src/core/Directus/Database/Schema/SchemaFactory.php]: Let's change this to `SELECT COUNT` instead, otherwise it would fetch the whole table just to do this check.

File: src/core/Directus/Database/Schema/SchemaFactory.php [hunk 2]
```diff
@@ -160,14 +160,14 @@ public function alterTable($name, array $data)
         }
 
         $toChangeColumnsData = ArrayUtils::get($data, 'change', []);
-
+        
         // Throws an exception when trying to make the field required and there are items with no value for that field in collection
         foreach ($toChangeColumnsData as $column) {
             if($column['required']) {
-                $selectQuery = sprintf('SELECT * FROM `%s` WHERE `%s` IS NULL',$name,$column['field']);
+                $selectQuery = sprintf('SELECT COUNT(*) as "count" FROM `%s` WHERE `%s` IS NULL',$name,$column['field']);
```
Comment (WoLfulus) [inline src/core/Directus/Database/Schema/SchemaFactory.php]: Is there a reason why we're not using query builder here? I'm not sure where those parameters come from, and I'm not confident on merging this because of security issues.

Is it possible to change it to use a query builder instead?
