### PR TITLE
Fix #999

### LINKED ISSUE #999: File uploads over a certain size result in a 0 byte file.
# Bug Report

## Steps to Reproduce

1. Go to 'File Library' in the Admin app at [yourAPI]/admin
2. Click on '+' to add a new file, and upload a file over 17MB.
3. Admin app shows a green checkmark (successful upload)
4. Go to your storage (s3 bucket or directus/public/uploads/{projectname}/originals) and examine the uploaded file.

## Expected Behavior
Any file that you uploaded should have been uploaded successfully without any change, regardless of the file size.
## Actual Behavior
If upload file was over 17MB, the destination file exists and is named properly.  Size is 0 bytes.  Smaller files work normally.
## Other Context & Screenshots
In other installations of Directus, the cutoff file size was variously 25MB or 20MB.  In this setup, the cutoff is 17MB.

## Technical Details

- Device: Digital Ocean one-click LAMP server
- OS: Ubuntu 18.04
- Web Server: Apache 2.4.29
- PHP Version: 7.2.17
- Database: MySQL 5.7.26
- Install Method: cloned `master` branch
large_file
large_vs_small_file

### PR DESCRIPTION
**Pull request by hemratna**
1. Tested with 650 MB file size with 128MB `memory_limit`.
2. Tested with AWS S3 file upload.
3. Remove `charset` for non-image files

### CODE REVIEW

**Comment by benhaynes** [comment]
This is awesome!! Thanks @hemratna!

File: src/core/Directus/Database/TableGateway/BaseTableGateway.php [hunk 1]
```diff
@@ -400,13 +400,13 @@ public function addRecordByArray(array $recordData)
...
         // TODO: Move this somewhere more sensible, and don't read the whole file contents into memory
         // in the first place.
-        if (
-            array_key_exists('filename', $recordData) &&
-            array_key_exists('data', $recordData) &&
-            strlen($recordData['data']) > 25000000
-        ) {
-            $recordData = ['filename' => $recordData['filename']];
-        }
+        // if (
```
Comment (rijkvanzanten) [inline src/core/Directus/Database/TableGateway/BaseTableGateway.php]: We can get rid of this completely. No need to leave commented out code in the codebase 🙂

Comment (hemratna) [reply src/core/Directus/Database/TableGateway/BaseTableGateway.php]: @rijkvanzanten I removed the commented code. 🙂
